name: Deploy Profestor App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.20.2'

    - name: Install dependencies
      run: yarn

    - name: Run ESLint
      run: yarn lint

    - name: Build the app
      run: yarn build

    - name: Deploy to VPS
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avz --delete --exclude="node_modules"
        path: .
        remote_path: ${{ secrets.VPS_PATH }}
        remote_host: ${{ secrets.VPS_HOST }}
        remote_port: ${{ secrets.VPS_PORT }}
        remote_user: ${{ secrets.VPS_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}  

    - name: Setup and restart the app
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd ${{ secrets.VPS_PATH }}
          [ -f .env ] && rm .env
          touch .env
          echo "SLACK_APP_TOKEN=${{ secrets.SLACK_APP_TOKEN }}" >> .env
          echo "SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}" >> .env
          echo "SLACK_SIGNING_SECRET=${{ secrets.SLACK_SIGNING_SECRET }}" >> .env
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use 16.20.2
          npm install -g yarn
          yarn install
          if pm2 list | grep -q "profesor"; then
            pm2 restart profesor
          else
            pm2 start dist/index.js --name profesor
          fi

